// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nexsprintAPI.Data;

#nullable disable

namespace nexsprintAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250528024229_FixDescricaoTable")]
    partial class FixDescricaoTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("nexsprintAPI.Models.Modulo", b =>
                {
                    b.Property<int>("ModuloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PDF_Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotalPaginas")
                        .HasColumnType("int");

                    b.HasKey("ModuloId");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("nexsprintAPI.Models.User", b =>
                {
                    b.Property<string>("NomeUsuario")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("longtext");

                    b.HasKey("NomeUsuario");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("nexsprintAPI.Models.UserModulo", b =>
                {
                    b.Property<string>("NomeUsuario")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<double>("Progresso")
                        .HasColumnType("double");

                    b.HasKey("NomeUsuario", "ModuloId");

                    b.HasIndex("ModuloId");

                    b.ToTable("UsersModulos");
                });

            modelBuilder.Entity("nexsprintAPI.Models.UserModulo", b =>
                {
                    b.HasOne("nexsprintAPI.Models.Modulo", "Modulo")
                        .WithMany("UsersModulos")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nexsprintAPI.Models.User", "User")
                        .WithMany("UsersModulos")
                        .HasForeignKey("NomeUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("nexsprintAPI.Models.Modulo", b =>
                {
                    b.Navigation("UsersModulos");
                });

            modelBuilder.Entity("nexsprintAPI.Models.User", b =>
                {
                    b.Navigation("UsersModulos");
                });
#pragma warning restore 612, 618
        }
    }
}
